### ISSUE TITLE
你好！我想问一下这个接口怎么改为我的？

### ISSUE THREAD

**Issue by jinhuashisizhou** [yaoshanliang/ssha-miniprogram#3]
不怎么懂技术，我们的官网用的织梦系统，这个小程序接口怎么改为我们的?请教一下！谢谢

**Comment by yaoshanliang** [comment]
@jinhuashisizhou 

织梦和wordpress格式不一样的吧~~

我的是把wordpress的格式显示在小程序里的，织梦的则需要修改代码里对应的字段。

(可以接~~)

**Comment by jinhuashisizhou** [comment]
我安装了wordpress，也安装了json插件，你在wordpress后台是怎么设置的呢？创建了什么栏目？还有数据是自动同步到小程序的吗？

**Comment by jinhuashisizhou** [comment]
你的QQ多少，请教一下你！谢谢了，公司让做的。。你这个案例正好我们公司也可以用

**Comment by yaoshanliang** [comment]
@jinhuashisizhou 

后台开启插件

小程序里修改对应的服务器地址，让它读取网站的数据。

**Comment by jinhuashisizhou** [comment]
我开启了，发布了几篇文章，json接口里有数据，但是小程序这块不显示。。

**Comment by jinhuashisizhou** [comment]
我的QQ2507892954 谢谢请教一下。。

**Comment by yaoshanliang** [comment]
@jinhuashisizhou 好的~

**Comment by jinhuashisizhou** [comment]
@yaoshanliang 谢谢你！
