### ISSUE TITLE
我拉取的是最新版本的 小程序ide里面打开后没有东西显示

### ISSUE THREAD

**Issue by YuyangHYY** [yaoshanliang/ssha-miniprogram#5]
我拉取后有尝试git checkout api，提示`Branch 'api' set up to track remote branch 'api' from 'origin'.`
要怎样才能显示数据呢，或者只是显示第一个版本 静态的新闻也是可以。

**Comment by YuyangHYY** [comment]
然后我执行了一下这个，还是在ide不显示数据
<img width="747" alt="2018-12-03 22 20 42" src="https://user-images.githubusercontent.com/19391002/49379322-caafeb00-f749-11e8-9ab0-a77f9eec348f.png">

**Comment by yaoshanliang** [comment]
用`git checkout static`获取静态页面，数据写死的。api需要后台支持

**Comment by YuyangHYY** [comment]
@yaoshanliang 好的 问题解决了 忘记试一下`static`了，谢谢🙏
